<a href="https://colab.research.google.com/github/Vaishnavi644/numpy/blob/main/Numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


##Introduction to Numpy

NumPy (Numerical Python) is one of the most important libraries in Python for numerical computing and data analysis. It provides a powerful N-dimensional array object along with a collection of functions for performing mathematical, statistical, and logical operations efficiently.

NumPy is widely used in Data Science, Machine Learning, Artificial Intelligence, Computer Vision, Scientific Computing, and Deep Learning. Many popular libraries such as Pandas, Scikit-learn, TensorFlow, and PyTorch are built upon concepts introduced by NumPy.


### Why NumPy?

Python lists are flexible but can become slow and memory-intensive when working with large amounts of numerical data. NumPy solves this problem by storing data in optimized arrays that are:

* Faster than Python lists
* More memory efficient
* Easier to perform mathematical operations on
* Suitable for handling large datasets


### Key Features of NumPy


- **N-Dimensional Arrays (ndarray):** NumPy provides a special array object that can store data in one, two, or multiple dimensions efficiently.

- **High Performance:** NumPy arrays are faster and more memory-efficient than Python lists, making them ideal for handling large amounts of data.

- **Broadcasting:** NumPy can perform operations on arrays of different shapes automatically without requiring extra code.

- **Vectorization:** Mathematical operations can be applied to entire arrays at once, eliminating the need for many loops and improving speed.

- **Mathematical Functions:** NumPy offers a wide range of built-in functions for calculations such as square roots, logarithms, trigonometric functions, and more.

- **Statistical Operations:** Easily calculate mean, median, standard deviation, variance, minimum, maximum, and other statistics.

- **Linear Algebra Support:** NumPy provides tools for matrix operations, matrix multiplication, determinants, inverses, and other linear algebra computations.

- **Random Number Generation:** Generate random numbers, samples, and distributions for simulations, testing, and machine learning applications.

- **Easy Integration:** NumPy works seamlessly with popular libraries such as Pandas, Matplotlib, Scikit-learn, TensorFlow, and PyTorch.


### Applications of NumPy

* Data Analysis
* Machine Learning
* Artificial Intelligence
* Image Processing
* Scientific Research
* Financial Modeling
* Signal Processing

### Learning Objectives

In this notebook, I will explore:

1. Array Creation and Attributes
2. Data Types
3. Multi-Dimensional Arrays
4. Indexing and Slicing
5. Vectorization
6. Broadcasting
7. Vector Norms
8. Statistical Functions
9. Mathematical Functions
10. Working with Images as Matrices

By the end of this notebook, I will have a strong foundation in NumPy and understand how it is used in real-world Data Science and Machine Learning workflows.


## Importing NumPy

Before using NumPy, we need to import it. By convention, NumPy is always
imported with the alias `np`. This is a universal standard followed by
the entire Python and Data Science community.

In [ ]:
import numpy as np
import time

arr=np.array([1,2,3])
print("Array =", arr)
print(type(arr))

Array = [1 2 3]
<class 'numpy.ndarray'>


## Array Creation


### From Python Lists
The most basic way to create a NumPy array is by passing a Python list
to `np.array()`.

In [ ]:
arr_1D=np.array([1,2,3])
print("Array 1D:", arr_1D)
arr_2D=np.array([[1,2,3],[4,5,6]])
print("Array 2D:", arr_2D,arr_2D.dtype,arr_2D.shape)

Array 1D: [1 2 3]
Array 2D: [[1 2 3]
 [4 5 6]] int64 (2, 3)
['1' '2' '3' '4' 'home'] <class 'numpy.ndarray'> <U21 (5,)


In [ ]:
arr=np.array([1,2,3,4,'home'])
print(arr,type(arr),arr.dtype,arr.shape)

['1' '2' '3' '4' 'home'] <class 'numpy.ndarray'> <U21 (5,)


#### Homogeneity & Type Upcasting

NumPy arrays are **homogeneous** — all elements must be of the same data type.

When mixed types are passed, NumPy automatically converts all elements
to a common type. This is called **Type Upcasting**.

**Upcasting Priority:**
`int` → `float` → `complex` → `string`

- `int` + `float` → **float**
- `int` + `string` → **string**
- `float` + `string` → **string**

> String is the final fallback as it can represent any value.

## Python List vs NumPy Array

| Feature | Python List | NumPy Array |
|--------|------------|-------------|
| Data Types | Can hold mixed types | Homogeneous (same type) |
| Speed | Slower | Faster |
| Memory | More memory | Less memory |
| Math Operations | Need loops | Direct operations |
| Syntax | `my_list = [1,2,3]` | `np.array([1,2,3])` |

In [ ]:
py_list=([1,2,3])
print("Python List Multiplication: ",py_list*2)

np_array=np.array([1,2,3])
print("Python Array Multiplication: ", np_array*2)

import time
start=time.time()
py_list=[i*2 for i in range(1000)]
print("\n List operation time:", time.time()-start)

start=time.time()
np_array=np.arange(1000)*2
print("\n Numpy_Array operation time:", time.time()-start)

Python List Multiplication:  [1, 2, 3, 1, 2, 3]
Python Array Multiplication:  [2 4 6]

 List operation time: 0.00016498565673828125

 Numpy_Array operation time: 0.00036263465881347656


####Execution Performance

#####Python list

In [ ]:
size=100_000_00

py_list=list(range(size))
start=time.time()
sq_list=[x**2 for x in py_list]
end=time.time()
print(f"Python list time= {end-start} seconds")


Python list time= 0.8255126476287842 seconds


#####Numpy Array

In [ ]:
np_arr=np.array(py_list)
start=time.time()
sq_arr=np_arr**2
end=time.time()
print(f"Numpy Arrays time= {end-start} seconds")

Numpy Arrays time= 0.16009521484375 seconds


#####Memory

In [ ]:
import sys

print (f" Python list Size ={sys.getsizeof(py_list)*len(py_list)} bytes")

print (f" Numpy Array Size ={np_arr.nbytes} bytes")

 Python list Size =800000560000000 bytes
 Numpy Array Size =80000000 bytes


## Creating Arrays from Scratch

### Constant Arrays

Constant arrays are arrays pre-filled with a fixed value.
Useful for **initializing arrays** before filling them with actual data,
which is a common pattern in Machine Learning and Scientific Computing.

| Function | Description |
|----------|-------------|
| `np.zeros(shape)` | Fills array with `0` |
| `np.ones(shape)` | Fills array with `1` |
| `np.full(shape, value)` | Fills array with any specific `value` |

> **Note:** By default, `np.zeros` and `np.ones` create `float64` arrays.
> Pass `dtype=np.int64` to get integers instead.

In [ ]:
zeros=np.zeros((3,4), dtype="int64")
print("Zeros arrays:\n ", zeros)

ones=np.ones((3,4))
print("ones arrays:\n ", ones)

full=np.full((3,4),7)
print("full arrays:\n ", full)

Zeros arrays:
  [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
ones arrays:
  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full arrays:
  [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


### Range Based Arrays

Used to create arrays with a sequence of values.

| Function | Description |
|----------|-------------|
| `np.arange(start, stop, step)` | Values from start to stop with a fixed step |
| `np.linspace(start, stop, n)` | `n` evenly spaced values between start and stop |

> **Note:** In `np.arange` stop is **exclusive**.
> In `np.linspace` stop is **inclusive**.

In [ ]:
sequence=np.arange(1,10,2)
print("Sequence arrays:\n ", sequence)

arr5=np.linspace(1,100,4)
print("Evenly spaced arrays:\n ", arr5, arr5.shape)

Sequence arrays:
  [1 3 5 7 9]
[1 3 5 7 9]
Evenly spaced arrays:
  [  1.  34.  67. 100.] (4,)


### Special Arrays

| Function | Description |
|----------|-------------|
| `np.eye(n)` | Identity matrix of size `n x n` with `1s` on the diagonal |
| `np.identity(n)` | Same as `np.eye()` but strictly square only |
| `np.random.random(shape)` | Array with random float values between `0` and `1` |

> **Difference:** `np.eye()` is more flexible — it allows you to shift
> the diagonal using the `k` parameter. `np.identity()` is strictly square
> with the diagonal always in the center.

In [ ]:
eye=np.eye((3), dtype=np.int64)
print("Eye Array\n:", eye)

id=np.identity(2)
print("identity arrays:\n ", id)

random=np.random.random((3,4))
print("random arrays:\n ", random)

Eye Array
: [[1 0 0]
 [0 1 0]
 [0 0 1]]
identity arrays:
  [[1. 0.]
 [0. 1.]]
random arrays:
  [[0.52432566 0.69876442 0.63590192 0.59032357]
 [0.81293527 0.17477386 0.65716351 0.85162481]
 [0.47483738 0.98117473 0.0326182  0.73418399]]


##Vector Matrix and Tensor

In NumPy, arrays are categorized by the number of dimensions they have.

| Type | Dimensions | Example Shape |
|------|-----------|---------------|
| **Vector** | 1D | `(n,)` |
| **Matrix** | 2D | `(rows, cols)` |
| **Tensor** | 3D or more | `(depth, rows, cols)` |

**Vector** — A single row or column of values.
Used to represent features of one data point in Machine Learning.

**Matrix** — A 2D grid of values with rows and columns.
Used to represent datasets, images in grayscale, weights in Neural Networks.

**Tensor** — 3 or more dimensions.
Used to represent colored images (height, width, channels),
video data, and batches of data in Deep Learning.

In [ ]:
vector=np.array([1,2,3,4])
print("Vector :", vector)

matrix=np.array([[1,2,3],
                 [4,5,6],
                 [6,7,8]])
print("Matrix :\n", matrix)

tensor=np.array([[[1,2],[3,4]],
                 [[6,7],[7,8]]])
print("Tensor :\n", tensor)

Vector : [1 2 3 4]
Matrix :
 [[1 2 3]
 [4 5 6]
 [6 7 8]]
Tensor :
 [[[1 2]
  [3 4]]

 [[6 7]
  [7 8]]]


## Array Properties

Every NumPy array has a set of built-in properties that describe its
structure and the type of data it holds.

| Property | Description |
|----------|-------------|
| `.shape` | Tuple representing size of each dimension `(rows, cols)` |
| `.ndim` | Number of dimensions |
| `.size` | Total number of elements |
| `.dtype` | Data type of the elements |

In [ ]:
arr=np.array([[1,2,3],
              [5,6,7]])
print("Shape: ", arr.shape)
print("Dimension: ", arr.ndim)
print("Size: ", arr.size)
print("DType: ", arr.dtype)

Shape:  (2, 3)
Dimension:  2
Size:  6
DType:  int64


In [ ]:
arr=np.array([[1,2,3],
              [5,6.8,7]])
print("Shape: ", arr.shape)
print("Dimension: ", arr.ndim)
print("Size: ", arr.size)
print("DType: ", arr.dtype)

In [ ]:
arr=np.array([[1,2,3],
              [5,True,7]])
print("Shape: ", arr.shape)
print("Dimension: ", arr.ndim)
print("Size: ", arr.size)
print("DType: ", arr.dtype)

In [ ]:
arr=np.array([[1,2,3],
              [5,"6.8",7]])
print("Shape: ", arr.shape)
print("Dimension: ", arr.ndim)
print("Size: ", arr.size)
print("DType: ", arr.dtype)

## Type Casting

We already saw that NumPy automatically upcasts when mixed types are passed.
But we can also **manually cast** an array to a specific type using `.astype()`.

| Method | Description |
|--------|-------------|
| `arr.astype(np.int64)` | Convert to integer |
| `arr.astype(np.float64)` | Convert to float |
| `arr.astype(np.bool_)` | Convert to boolean |
| `arr.astype(str)` | Convert to string |

> **Note:** `.astype()` always returns a **new array** — it does not
> modify the original.

In [ ]:
arr=np.array([[1,2,3],
              [5,6,7]])
float_arr=arr.astype(np.float64)
print(float_arr,float_arr.dtype)

[[1. 2. 3.]
 [5. 6. 7.]] float64


# Operations on Numpy Arrays

### 1. Reshaping Arrays

Reshaping allows us to change the **shape** of an array without
changing its **data** or **size**.

| Function | Description |
|----------|-------------|
| `.reshape(shape)` | Returns a new array with the given shape |
| `.ravel()` | Flattens array to 1D — returns a **view** |
| `.flatten()` | Flattens array to 1D — returns a **copy** |
| `.T` | Transposes the array (rows become columns) |

> **Rule:** Total number of elements must remain the same before
> and after reshaping.
> For example, a `(2, 6)` array can be reshaped to `(3, 4)`, `(4, 3)`,
> `(12,)` but **not** `(3, 5)`.

> **ravel vs flatten:** Both flatten the array but `ravel` returns a
> **view** (modifying it affects the original) while `flatten` returns
> a **copy** (original stays safe).

In [ ]:
arr=np.arange(12)
print("Array: \n", arr)

reshaped=arr.reshape((4,3))
print(" Reshaped Array: \n", reshaped)

flatten=reshaped.flatten()
print(" Flatten Array: \n", flatten)

raveled=reshaped.ravel()
print("Raveled Array: \n", raveled)

Transpose=reshaped.T
print("Transpose Array:\n ", Transpose)

Array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
 Reshaped Array: 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
 Flatten Array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose Array:
  [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


###2. Indexing

Indexing allows us to **access specific elements** from a NumPy array.

| Operation | Syntax | Description |
|-----------|--------|-------------|
| Single element | `arr[i]` | Element at index `i` in 1D |
| 2D element | `arr[i, j]` | Element at row `i`, column `j` |
| Negative index | `arr[-1]` | Last element |



In [ ]:
arr_2D=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print("Specific element: ", arr_2D[1,2]) # row, column
print("Specific row only: ",arr_2D[1])
print("Specific column only: ",arr_2D[:,2])

Specific element:  6
Specific row only:  [4 5 6]
Specific column only:  [3 6 9]


###3. Slicing

Slicing allows us to **extract a portion** of an array.
Syntax: `arr[start:stop:step]`

| Operation | Syntax | Description |
|-----------|--------|-------------|
| Row slice | `arr[i:j]` | Rows from `i` to `j` (exclusive) |
| Column slice | `arr[:, j:k]` | Columns from `j` to `k` |
| Sub-array | `arr[i:j, k:l]` | Rows `i:j` and columns `k:l` |
| Step slice | `arr[::2]` | Every 2nd element |

> **Important:** Slicing returns a **view** not a copy — modifying
> the slice will modify the original array.
> Use `.copy()` to avoid this.

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing :", arr[3:7])
print(" With step: ", arr[3:8:2])
print("Negative Indexing : ", arr[-3])
print("All elements Indexing : ", arr[:])
print("All elements Indexing : ", arr[::2])

Basic Slicing : [4 5 6 7]
 With step:  [4 6 8]
Negative Indexing :  8
All elements Indexing :  [ 1  2  3  4  5  6  7  8  9 10]
All elements Indexing :  [1 3 5 7 9]


#### Copy vs View

When we slice a NumPy array, the result is a **view** not a copy.
This means both the original and the slice point to the **same data in memory**.

| | View | Copy |
|---|------|------|
| Created by | Slicing, `ravel()` | `arr.copy()`, fancy indexing, `flatten()` |
| Memory | Shares original memory | Own independent memory |
| Modifying affects original? | ✅ Yes | ❌ No |

> **Rule:** If you want to modify a slice without affecting the
> original array — always use `.copy()`.

In [ ]:
list=[1,2,3,4,5]
sub_list=list[1:3]
print(sub_list)
sub_list[0]=200
print(sub_list)
print(list)


[2, 3]
[200, 3]
[1, 2, 3, 4, 5]


In [ ]:
arr=np.array([1,2,3,4,5])
# sub_arr=arr[1:3]
sub_arr=arr[1:3].copy()
print(sub_arr)
sub_arr[0]=200
print(sub_arr)
print(arr)

[2 3]
[200   3]
[1 2 3 4 5]


###4. Fancy Indexing & Boolean Indexing

Both allow accessing multiple elements at once but in different ways.

**Fancy Indexing** — access elements by passing a list of indices.
**Boolean Indexing** — access elements based on a condition.

| Operation | Syntax | Description |
|-----------|--------|-------------|
| Multiple rows | `arr[[0, 2, 4]]` | Rows 0, 2 and 4 |
| Multiple elements | `arr[[0, 1], [2, 3]]` | Elements at `(0,2)` and `(1,3)` |
| Filter elements | `arr[arr > 5]` | All elements greater than 5 |
| Multiple conditions | `arr[(arr > 2) & (arr < 8)]` | Elements between 2 and 8 |
| Using OR | `arr[(arr < 2) \| (arr > 8)]` | Elements less than 2 or greater than 8 |

> **Fancy Indexing** always returns a **copy** not a view.

> **Boolean Indexing:** Always use `&` and `|` instead of `and` and `or`
> for combining conditions in NumPy.

####Filter

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
indices=[0,2,4]
print(arr[indices])

print(arr[arr>5])

[1 3 5]
[ 6  7  8  9 10]


#### Filters with Mask

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

mask = arr > 5
print("Mask: ", mask)
print("Filtered elements: ", arr[mask])

Mask:  [False False False False False  True  True  True  True  True]
Filtered elements:  [ 6  7  8  9 10]


#### np.where()

`np.where(condition, value_if_true, value_if_false)`

Works like an if-else applied to every element of the array.

- If condition is `True` → use `value_if_true`
- If condition is `False` → use `value_if_false`

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

result = np.where(arr > 5, arr * 4, arr)
print(result)

[ 1  2  3  4  5 24 28 32 36 40]


###5. Sorting

| Function | Description |
|----------|-------------|
| `np.sort(arr)` | Returns a **sorted copy** of the array |
| `arr.sort()` | Sorts the array **in-place** |
| `np.argsort(arr)` | Returns **indices** that would sort the array |

> **`np.sort()` vs `arr.sort()`:** `np.sort()` returns a new sorted array
> leaving the original unchanged. `arr.sort()` modifies the original array directly.

> **`np.argsort()`:** Useful when you need to know the **position** of
> elements in sorted order rather than the values themselves.

In [ ]:
arr = np.array([2, 1, 4, 7, 3, 9, 4])
print("Sorted:         ", np.sort(arr))
print("Argsort:        ", np.argsort(arr))

arr_2D = np.array([[1, 4], [3, 1], [2, 1]])
print("Sorted axis=0:\n", np.sort(arr_2D, axis=0))
print("Sorted axis=1:\n", np.sort(arr_2D, axis=1))

Sorted Array:  [1 2 3 4 4 7 9]
Sorted 2D Array:  [[1 1]
 [2 1]
 [3 4]]
Sorted 2D Array:  [[1 4]
 [1 3]
 [1 2]]


In [ ]:
numbers=np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers=numbers[numbers%2==0]
print("Even Numbers: ", even_numbers)
odd_numbers=numbers[numbers%2!=0]
print("Odd Numbers: ", odd_numbers)

Even Numbers:  [ 2  4  6  8 10]
Odd Numbers:  [1 3 5 7 9]


> **axis=0** → sorts column wise (top to bottom)
> **axis=1** → sorts row wise (left to right)

## NumPy Data Types

NumPy provides its own data types which are more precise and
memory efficient than Python's built-in types.

| Data Type | Code | Description |
|-----------|------|-------------|
| `np.int8` to `np.int64` | `i1` to `i8` | Signed integers |
| `np.uint8` to `np.uint64` | `u1` to `u8` | Unsigned integers (no negatives) |
| `np.float16` to `np.float64` | `f2` to `f8` | Decimal numbers |
| `np.complex64` to `np.complex128` | `c8` to `c16` | Complex numbers |
| `np.bool_` | `?` | Boolean (True / False) |
| `np.str_` | `U` | Unicode string |

> **Why different sizes?** The number represents **bits** used in memory.
> Larger size = more precision but more memory.
> For example `int8` can hold `-128 to 127` while `int64` can hold
> much larger values.

> **In Machine Learning:** `float32` is the most commonly used dtype
> as it balances precision and memory efficiently.

In [ ]:
arr=np.array([1,2,3,4,5])
print(arr,arr.dtype)

arr2=np.array([1,2.3,3,4,5])
print(arr2,arr2.dtype)

arr3=np.array([1,2.3,3,4,'5'])
print(arr3,arr3.dtype)

arr4=np.array([3+5j])
arr5=np.array([4+7j])
print(arr4+arr5,arr4.dtype)


[1 2 3 4 5] int64
[1.  2.3 3.  4.  5. ] float64
['1' '2.3' '3' '4' '5'] <U32
[7.+12.j] complex128
[3.12 '5' {1, 2, 3}] object


> **`np.object_`:** When NumPy cannot find a common type for all elements,
> it falls back to `object` dtype — storing each element as a Python object.
> This is the least efficient dtype and should be avoided where possible.

In [ ]:
arr6=np.array([3.12,'5',{1,2,3}])
print(arr6,arr6.dtype)

int → uint → float → complex → bool → str → object