<a href="https://colab.research.google.com/github/Vaishnavi644/numpy/blob/main/Numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import time

arr=np.array([1,2,3])
print("Array =", arr)
print(type(arr))

Array = [1 2 3]
<class 'numpy.ndarray'>


In [ ]:
#Creating Array from List
arr_1D=np.array([1,2,3])
print("Array 1D:", arr_1D)
arr_2D=np.array([[1,2,3],[4,5,6]])
print("Array 2D:", arr_2D,arr_2D.dtype,arr_2D.shape)


# numpy array is homogeneous so it try to make the array homogenous converting it to string array
#NumPy sees both integers and a string in the same list.
#It has to choose a dtype that can represent every element without losing information.
arr=np.array([1,2,3,4,'home'])
print(arr,type(arr),arr.dtype,arr.shape)


Array 1D: [1 2 3]
Array 2D: [[1 2 3]
 [4 5 6]] int64 (2, 3)
['1' '2' '3' '4' 'home'] <class 'numpy.ndarray'> <U21 (5,)


List v/s numpy Arrays

In [ ]:
py_list=([1,2,3])
print("Python List Multiplication: ",py_list*2)

np_array=np.array([1,2,3])
print("Python Array Multiplication: ", np_array*2)

import time
start=time.time()
py_list=[i*2 for i in range(1000)]
print("\n List operation time:", time.time()-start)

start=time.time()
np_array=np.arange(1000)*2
print("\n Numpy_Array operation time:", time.time()-start)

Python List Multiplication:  [1, 2, 3, 1, 2, 3]
Python Array Multiplication:  [2 4 6]

 List operation time: 0.00016498565673828125

 Numpy_Array operation time: 0.00036263465881347656


In [ ]:
# Execution Performance
size=100_000_000

# Python list
py_list=list(range(size))
start=time.time()
sq_list=[x**2 for x in py_list]
end=time.time()
print(f"Python list time= {end-start} seconds")


# Numpy Arrays
np_arr=np.array(py_list)
start=time.time()
sq_arr=np_arr**2
end=time.time()
print(f"Numpy Arrays time= {end-start} seconds")

Python list time= 9.006068229675293 seconds
Numpy Arrays time= 0.8446969985961914 seconds


In [ ]:
# Memory
import sys

print (f" Python list Size ={sys.getsizeof(py_list)*len(py_list)} bytes")

print (f" Numpy Array Size ={np_arr.nbytes} bytes")

 Python list Size =80000005600000000 bytes
 Numpy Array Size =800000000 bytes


Creating Array form scratch

In [ ]:
zeros=np.zeros((3,4), dtype="int64") #we specify the datatype as int by default it is float
print("Zeros arrays:\n ", zeros)

ones=np.ones((3,4))
print("ones arrays:\n ", ones)

full=np.full((3,4),7)
print("full arrays:\n ", full)

eye=np.eye((3), dtype=np.int64)
print("Eye Array\n:", eye)

random=np.random.random((3,4))
print("random arrays:\n ", random)

sequence=np.arange(1,10,2) #Start stop step
print("Sequence arrays:\n ", sequence)

id=np.identity(2)
print("identity arrays:\n ", id)

#range(start,end,step) end is inclusive
r=np.arange(1,10,2)
print(r)

arr5=np.linspace(1,100,4) # evenly spaced array
print("Evenly spaced arrays:\n ", arr5, arr5.shape)

Zeros arrays:
  [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
ones arrays:
  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full arrays:
  [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
Eye Array
: [[1 0 0]
 [0 1 0]
 [0 0 1]]
random arrays:
  [[0.46835895 0.83611521 0.14870983 0.68881916]
 [0.5260447  0.76098433 0.25411545 0.93817275]
 [0.30189079 0.08907932 0.59659283 0.74547125]]
Sequence arrays:
  [1 3 5 7 9]
identity arrays:
  [[1. 0.]
 [0. 1.]]
[1 3 5 7 9]
Evenly spaced arrays:
  [  1.  34.  67. 100.] (4,)


Vector Matrix and Tensor

In [ ]:
vector=np.array([1,2,3,4])
print("Vector :", vector)

matrix=np.array([[1,2,3],
                 [4,5,6],
                 [6,7,8]])
print("Matrix :\n", matrix)

tensor=np.array([[[1,2],[3,4]],
                 [[6,7],[7,8]]])
print("Tensor :\n", tensor)

Vector : [1 2 3 4]
Matrix :
 [[1 2 3]
 [4 5 6]
 [6 7 8]]
Tensor :
 [[[1 2]
  [3 4]]

 [[6 7]
  [7 8]]]


Array Properties

In [ ]:
arr=np.array([[1,2,3],
              [5,6,7]])
print("Shape: ", arr.shape) #the number of rows and columns
print("Dimension: ", arr.ndim) # dimensions
print("Size: ", arr.size) #total number of elements
print("DType: ", arr.dtype)

arr=np.array([[1,2,3],
              [5,6.8,7]])
print("Shape: ", arr.shape) #the number of rows and columns
print("Dimension: ", arr.ndim) # dimensions
print("Size: ", arr.size) #total number of elements
print("DType: ", arr.dtype)

arr=np.array([[1,2,3],
              [5,True,7]])
print("Shape: ", arr.shape) #the number of rows and columns
print("Dimension: ", arr.ndim) # dimensions
print("Size: ", arr.size) #total number of elements
print("DType: ", arr.dtype)

arr=np.array([[1,2,3],
              [5,"6.8",7]])
print("Shape: ", arr.shape) #the number of rows and columns
print("Dimension: ", arr.ndim) # dimensions
print("Size: ", arr.size) #total number of elements
print("DType: ", arr.dtype)

Shape:  (2, 3)
Dimension:  2
Size:  6
DType:  int64
Shape:  (2, 3)
Dimension:  2
Size:  6
DType:  float64
Shape:  (2, 3)
Dimension:  2
Size:  6
DType:  int64
Shape:  (2, 3)
Dimension:  2
Size:  6
DType:  <U21


In [ ]:
#Type casting
arr=np.array([[1,2,3],
              [5,6,7]])
float_arr=arr.astype(np.float64)
print(float_arr,float_arr.dtype)

[[1. 2. 3.]
 [5. 6. 7.]] float64


# Operations on Numpy **Arrays**

1. Array Reshaping

In [ ]:
arr=np.arange(12)
print("Array: \n", arr)

reshaped=arr.reshape((4,3))
print(" Reshaped Array: \n", reshaped)

flatten=reshaped.flatten()
print(" Flatten Array: \n", flatten)

# ravel (Returns view instead of copy )
raveled=reshaped.ravel()
print("Raveled Array: \n", raveled)

Transpose=reshaped.T
print("Transpose Array:\n ", Transpose)

Array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
 Reshaped Array: 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
 Flatten Array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose Array:
  [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


2. Indexing

In [ ]:
arr_2D=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print("Specific element: ", arr_2D[1,2]) # row, column
print("Specific row only: ",arr_2D[1])
print("Specific column only: ",arr_2D[:,2])

Specific element:  6
Specific row only:  [4 5 6]
Specific column only:  [3 6 9]


3. Slicing

In [ ]:
# slicing
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing :", arr[3:7])
print(" With step: ", arr[3:8:2])
print("Negative Indexing : ", arr[-3])
print("All elements Indexing : ", arr[:])
print("All elements Indexing : ", arr[::2])

Basic Slicing : [4 5 6 7]
 With step:  [4 6 8]
Negative Indexing :  8
All elements Indexing :  [ 1  2  3  4  5  6  7  8  9 10]
All elements Indexing :  [1 3 5 7 9]


4. Fancy Indexing & boolean indexing

In [ ]:

arr=np.array([1,2,3,4,5,6,7,8,9,10])
indices=[0,2,4]
print(arr[indices])
#boolean indexing
print(arr[arr>5])


#where_result=np.where arr>5)
#print(where_result)
#print(" NP where: ", arr[where_result])

[1 3 5]
[ 6  7  8  9 10]


# Sorting

In [ ]:
arr_unsorted=np.array([2,1,4,7,3,9,4])
print("Sorted Array: ", np.sort(arr_unsorted))

arr_2D_unsorted=np.array([[1,4],[3,1],[2,1]])
print("Sorted 2D Array: ", np.sort(arr_2D_unsorted, axis=0))
print("Sorted 2D Array: ", np.sort(arr_2D_unsorted, axis=1))

Sorted Array:  [1 2 3 4 4 7 9]
Sorted 2D Array:  [[1 1]
 [2 1]
 [3 4]]
Sorted 2D Array:  [[1 4]
 [1 3]
 [1 2]]


# Filter

In [ ]:
numbers=np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers=numbers[numbers%2==0]
print("Even Numbers: ", even_numbers)
odd_numbers=numbers[numbers%2!=0]
print("Odd Numbers: ", odd_numbers)

Even Numbers:  [ 2  4  6  8 10]
Odd Numbers:  [1 3 5 7 9]


# Filters with Mask

In [ ]:
mask=numbers>5
print("Numbers greater than 5: ", numbers[mask])

Numbers greater than 5:  [ 6  7  8  9 10]


Fancy indexing and np.where()italicized text

In [ ]:
condition_array=np.where(numbers>5, numbers*4, numbers)
print(condition_array)
# Meaning of above line of code are
#if(number>5){ number *4 }
#else{ numbers }

[ 1  2  3  4  5 24 28 32 36 40]


In [ ]:
a2 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])
print(a2[-1])

[7 8 9]


Copy and View in Slice

In [ ]:
# list=[1,2,3,4,5]
# sub_list=list[1:3]
# print(sub_list)
# sub_list[0]=200
# print(sub_list)
# print(list)


arr=np.array([1,2,3,4,5])
# sub_arr=arr[1:3]
sub_arr=arr[1:3].copy() # creates the copy of the view of the sub_arr. Use to create copy



print(sub_arr)
sub_arr[0]=200
print(sub_arr)
print(arr)



[2 3]
[200   3]
[1 2 3 4 5]


Numpy datatypes

In [ ]:
arr=np.array([1,2,3,4,5])
print(arr,arr.dtype)

arr2=np.array([1,2.3,3,4,5])
print(arr2,arr2.dtype)

arr3=np.array([1,2.3,3,4,'5'])
print(arr3,arr3.dtype)

arr4=np.array([3+5j])
arr5=np.array([4+7j])
print(arr4+arr5,arr4.dtype)

arr6=np.array([3.12,'5',{1,2,3}])
print(arr6,arr6.dtype)


[1 2 3 4 5] int64
[1.  2.3 3.  4.  5. ] float64
['1' '2.3' '3' '4' '5'] <U32
[7.+12.j] complex128
[3.12 '5' {1, 2, 3}] object


### Multi-dimensional Arrays